export const PROBLEMS = [
  {
    cat: "Arrays & Hashing",
    icon: "🧩",
    problems: [
      { id: 217, name: "Contains Duplicate", diff: "easy" },
      { id: 242, name: "Valid Anagram", diff: "easy" },
      { id: 1, name: "Two Sum", diff: "easy" },
      { id: 49, name: "Group Anagrams", diff: "medium" },
      { id: 347, name: "Top K Frequent Elements", diff: "medium" },
      { id: 238, name: "Product of Array Except Self", diff: "medium" },
      { id: 36, name: "Valid Sudoku", diff: "medium" },
      { id: 271, name: "Encode and Decode Strings", diff: "medium" },
      { id: 128, name: "Longest Consecutive Sequence", diff: "medium" },
    ],
  },
  {
    cat: "Two Pointers",
    icon: "👆",
    problems: [
      { id: 125, name: "Valid Palindrome", diff: "easy" },
      { id: 167, name: "Two Sum II", diff: "medium" },
      { id: 15, name: "3Sum", diff: "medium" },
      { id: 11, name: "Container With Most Water", diff: "medium" },
      { id: 42, name: "Trapping Rain Water", diff: "hard" },
    ],
  },
  {
    cat: "Sliding Window",
    icon: "🪟",
    problems: [
      { id: 121, name: "Best Time to Buy & Sell Stock", diff: "easy" },
      {
        id: 3,
        name: "Longest Substring Without Repeating Chars",
        diff: "medium",
      },
      {
        id: 424,
        name: "Longest Repeating Character Replacement",
        diff: "medium",
      },
      { id: 567, name: "Permutation in String", diff: "medium" },
      { id: 76, name: "Minimum Window Substring", diff: "hard" },
      { id: 239, name: "Sliding Window Maximum", diff: "hard" },
    ],
  },
  {
    cat: "Stack",
    icon: "📚",
    problems: [
      { id: 20, name: "Valid Parentheses", diff: "easy" },
      { id: 155, name: "Min Stack", diff: "medium" },
      { id: 150, name: "Evaluate Reverse Polish Notation", diff: "medium" },
      { id: 22, name: "Generate Parentheses", diff: "medium" },
      { id: 739, name: "Daily Temperatures", diff: "medium" },
      { id: 853, name: "Car Fleet", diff: "medium" },
      { id: 84, name: "Largest Rectangle in Histogram", diff: "hard" },
    ],
  },
  {
    cat: "Binary Search",
    icon: "🔍",
    problems: [
      { id: 704, name: "Binary Search", diff: "easy" },
      { id: 74, name: "Search a 2D Matrix", diff: "medium" },
      { id: 875, name: "Koko Eating Bananas", diff: "medium" },
      { id: 153, name: "Find Minimum in Rotated Sorted Array", diff: "medium" },
      { id: 33, name: "Search in Rotated Sorted Array", diff: "medium" },
      { id: 981, name: "Time Based Key-Value Store", diff: "medium" },
      { id: 4, name: "Median of Two Sorted Arrays", diff: "hard" },
    ],
  },
  {
    cat: "Linked List",
    icon: "🔗",
    problems: [
      { id: 206, name: "Reverse Linked List", diff: "easy" },
      { id: 21, name: "Merge Two Sorted Lists", diff: "easy" },
      { id: 143, name: "Reorder List", diff: "medium" },
      { id: 19, name: "Remove Nth Node From End of List", diff: "medium" },
      { id: 138, name: "Copy List with Random Pointer", diff: "medium" },
      { id: 2, name: "Add Two Numbers", diff: "medium" },
      { id: 141, name: "Linked List Cycle", diff: "easy" },
      { id: 287, name: "Find the Duplicate Number", diff: "medium" },
      { id: 146, name: "LRU Cache", diff: "medium" },
      { id: 23, name: "Merge K Sorted Lists", diff: "hard" },
      { id: 25, name: "Reverse Nodes in k-Group", diff: "hard" },
    ],
  },
  {
    cat: "Trees",
    icon: "🌲",
    problems: [
      { id: 226, name: "Invert Binary Tree", diff: "easy" },
      { id: 104, name: "Maximum Depth of Binary Tree", diff: "easy" },
      { id: 543, name: "Diameter of Binary Tree", diff: "easy" },
      { id: 110, name: "Balanced Binary Tree", diff: "easy" },
      { id: 100, name: "Same Tree", diff: "easy" },
      { id: 572, name: "Subtree of Another Tree", diff: "easy" },
      { id: 235, name: "Lowest Common Ancestor of BST", diff: "medium" },
      { id: 102, name: "Binary Tree Level Order Traversal", diff: "medium" },
      { id: 199, name: "Binary Tree Right Side View", diff: "medium" },
      { id: 1448, name: "Count Good Nodes in Binary Tree", diff: "medium" },
      { id: 98, name: "Validate Binary Search Tree", diff: "medium" },
      { id: 230, name: "Kth Smallest Element in a BST", diff: "medium" },
      {
        id: 105,
        name: "Construct Tree from Preorder & Inorder",
        diff: "medium",
      },
      { id: 124, name: "Binary Tree Maximum Path Sum", diff: "hard" },
      { id: 297, name: "Serialize and Deserialize Binary Tree", diff: "hard" },
    ],
  },
  {
    cat: "Tries",
    icon: "🌳",
    problems: [
      { id: 208, name: "Implement Trie (Prefix Tree)", diff: "medium" },
      { id: 211, name: "Design Add and Search Words DS", diff: "medium" },
      { id: 212, name: "Word Search II", diff: "hard" },
    ],
  },
  {
    cat: "Heap / Priority Queue",
    icon: "⛰️",
    problems: [
      { id: 703, name: "Kth Largest Element in a Stream", diff: "easy" },
      { id: 1046, name: "Last Stone Weight", diff: "easy" },
      { id: 973, name: "K Closest Points to Origin", diff: "medium" },
      { id: 215, name: "Kth Largest Element in an Array", diff: "medium" },
      { id: 621, name: "Task Scheduler", diff: "medium" },
      { id: 355, name: "Design Twitter", diff: "medium" },
      { id: 295, name: "Find Median from Data Stream", diff: "hard" },
    ],
  },
  {
    cat: "Backtracking",
    icon: "↩️",
    problems: [
      { id: 78, name: "Subsets", diff: "medium" },
      { id: 39, name: "Combination Sum", diff: "medium" },
      { id: 40, name: "Combination Sum II", diff: "medium" },
      { id: 46, name: "Permutations", diff: "medium" },
      { id: 90, name: "Subsets II", diff: "medium" },
      { id: 79, name: "Word Search", diff: "medium" },
      { id: 131, name: "Palindrome Partitioning", diff: "medium" },
      { id: 17, name: "Letter Combinations of a Phone Number", diff: "medium" },
      { id: 51, name: "N-Queens", diff: "hard" },
    ],
  },
  {
    cat: "Graphs",
    icon: "🕸️",
    problems: [
      { id: 200, name: "Number of Islands", diff: "medium" },
      { id: 133, name: "Clone Graph", diff: "medium" },
      { id: 695, name: "Max Area of Island", diff: "medium" },
      { id: 417, name: "Pacific Atlantic Water Flow", diff: "medium" },
      { id: 130, name: "Surrounded Regions", diff: "medium" },
      { id: 994, name: "Rotting Oranges", diff: "medium" },
      { id: 286, name: "Walls and Gates", diff: "medium" },
      { id: 207, name: "Course Schedule", diff: "medium" },
      { id: 210, name: "Course Schedule II", diff: "medium" },
      { id: 684, name: "Redundant Connection", diff: "medium" },
      { id: 323, name: "Number of Connected Components", diff: "medium" },
      { id: 261, name: "Graph Valid Tree", diff: "medium" },
      { id: 127, name: "Word Ladder", diff: "hard" },
    ],
  },
  {
    cat: "Advanced Graphs",
    icon: "🔮",
    problems: [
      { id: 332, name: "Reconstruct Itinerary", diff: "hard" },
      { id: 1584, name: "Min Cost to Connect All Points", diff: "medium" },
      { id: 743, name: "Network Delay Time", diff: "medium" },
      { id: 778, name: "Swim in Rising Water", diff: "hard" },
      { id: 269, name: "Alien Dictionary", diff: "hard" },
      { id: 787, name: "Cheapest Flights Within K Stops", diff: "medium" },
    ],
  },
  {
    cat: "1-D Dynamic Programming",
    icon: "📐",
    problems: [
      { id: 70, name: "Climbing Stairs", diff: "easy" },
      { id: 746, name: "Min Cost Climbing Stairs", diff: "easy" },
      { id: 198, name: "House Robber", diff: "medium" },
      { id: 213, name: "House Robber II", diff: "medium" },
      { id: 5, name: "Longest Palindromic Substring", diff: "medium" },
      { id: 647, name: "Palindromic Substrings", diff: "medium" },
      { id: 91, name: "Decode Ways", diff: "medium" },
      { id: 322, name: "Coin Change", diff: "medium" },
      { id: 152, name: "Maximum Product Subarray", diff: "medium" },
      { id: 139, name: "Word Break", diff: "medium" },
      { id: 300, name: "Longest Increasing Subsequence", diff: "medium" },
      { id: 416, name: "Partition Equal Subset Sum", diff: "medium" },
    ],
  },
  {
    cat: "2-D Dynamic Programming",
    icon: "📊",
    problems: [
      { id: 62, name: "Unique Paths", diff: "medium" },
      { id: 1143, name: "Longest Common Subsequence", diff: "medium" },
      { id: 309, name: "Best Time to Buy/Sell with Cooldown", diff: "medium" },
      { id: 518, name: "Coin Change II", diff: "medium" },
      { id: 494, name: "Target Sum", diff: "medium" },
      { id: 97, name: "Interleaving String", diff: "medium" },
      { id: 329, name: "Longest Increasing Path in Matrix", diff: "hard" },
      { id: 115, name: "Distinct Subsequences", diff: "hard" },
      { id: 72, name: "Edit Distance", diff: "medium" },
      { id: 312, name: "Burst Balloons", diff: "hard" },
      { id: 10, name: "Regular Expression Matching", diff: "hard" },
    ],
  },
  {
    cat: "Greedy",
    icon: "💰",
    problems: [
      { id: 53, name: "Maximum Subarray", diff: "medium" },
      { id: 55, name: "Jump Game", diff: "medium" },
      { id: 45, name: "Jump Game II", diff: "medium" },
      { id: 134, name: "Gas Station", diff: "medium" },
      { id: 846, name: "Hand of Straights", diff: "medium" },
      {
        id: 1899,
        name: "Merge Triplets to Form Target Triplet",
        diff: "medium",
      },
      { id: 763, name: "Partition Labels", diff: "medium" },
      { id: 678, name: "Valid Parenthesis String", diff: "medium" },
    ],
  },
  {
    cat: "Intervals",
    icon: "📏",
    problems: [
      { id: 57, name: "Insert Interval", diff: "medium" },
      { id: 56, name: "Merge Intervals", diff: "medium" },
      { id: 435, name: "Non-overlapping Intervals", diff: "medium" },
      { id: 252, name: "Meeting Rooms", diff: "easy" },
      { id: 253, name: "Meeting Rooms II", diff: "medium" },
      {
        id: 1851,
        name: "Minimum Interval to Include Each Query",
        diff: "hard",
      },
    ],
  },
  {
    cat: "Math & Geometry",
    icon: "📐",
    problems: [
      { id: 202, name: "Happy Number", diff: "easy" },
      { id: 66, name: "Plus One", diff: "easy" },
      { id: 50, name: "Pow(x, n)", diff: "medium" },
      { id: 43, name: "Multiply Strings", diff: "medium" },
      { id: 2013, name: "Detect Squares", diff: "medium" },
      { id: 48, name: "Rotate Image", diff: "medium" },
      { id: 54, name: "Spiral Matrix", diff: "medium" },
      { id: 73, name: "Set Matrix Zeroes", diff: "medium" },
    ],
  },
  {
    cat: "Bit Manipulation",
    icon: "💾",
    problems: [
      { id: 136, name: "Single Number", diff: "easy" },
      { id: 191, name: "Number of 1 Bits", diff: "easy" },
      { id: 338, name: "Counting Bits", diff: "easy" },
      { id: 190, name: "Reverse Bits", diff: "easy" },
      { id: 268, name: "Missing Number", diff: "easy" },
      { id: 371, name: "Sum of Two Integers", diff: "medium" },
      { id: 7, name: "Reverse Integer", diff: "medium" },
    ],
  },
];
